<h1>Editar Álbum</h1>
<form action="<?= BASE_URL ?>update-album/<?= $album->ID_Album ?>" method="POST" class="my-4">
    <div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>Nombre</label>
                <input required name="name" type="text" class="form-control" value="<?= htmlspecialchars($album->nombre) ?>">
            </div>
        </div>
    </div>
    <div class="form-group">
        <label>Fecha de lanzamiento</label>
        <input required name="launchDate" type="date" class="form-control" value="<?= htmlspecialchars($album->lanzamiento) ?>">
    </div>
    <div class="form-group">
        <label>Cantidad de canciones</label>
        <input required name="nSongs" type="number" class="form-control" value="<?= htmlspecialchars($album->cantCanciones) ?>">
    </div>
    <div class="form-group">
        <label>Género</label>
        <input required name="genre" type="text" class="form-control" value="<?= htmlspecialchars($album->genero) ?>">
    </div>
    <div class="form-group">
        <label>Autor</label>
        <select name="ID_Autor" id="autor" class="form-control">
            <?php foreach ($autores as $autor): ?>
                <option value="<?= htmlspecialchars($autor->ID_Autor) ?>" <?= ($autor->ID_Autor == $album->ID_Autor) ? 'selected' : '' ?>>
                    <?= htmlspecialchars($autor->nombre) ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>
    <button type="submit" class="btn btn-primary mt-2">Guardar cambios</button>
</form>