<!-- formulario de alta de album -->
<form action="add-album" method="POST" class="my-4">
    <div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>Nombre</label>
                <input required name="name" type="text" class="form-control">
            </div>
        </div>
    </div>

    <div class="form-group">
        <label>fecha de lanzamiento</label>
        <input required name="launchDate" type="date" class="form-control">
    </div>
    <div class="form-group">
        <label>Cantidad de canciones</label>
        <input required name="nSongs" type="number" class="form-control">
    </div>

    <div class="form-group">
        <label>Genero</label>
        <input required name="genre" type="text" class="form-control">
    </div>

     <div class="form-group">
        <label>Autor</label>
        <select name="ID_Autor" id="autor" class="form-control">
            <?php foreach ($autores as $autor): ?>
                <option value="<?= htmlspecialchars($autor->ID_Autor) ?>">
                    <?= htmlspecialchars($autor->nombre) ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>

    <button type="submit" class="btn btn-primary mt-2">Agregar álbum al stock</button>
</form>
