<!-- formulario de alta de autor -->
<form action="add-autor" method="POST" class="my-4">
    <div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>Nombre autor</label>
                <input required name="name" type="text" class="form-control">
            </div>
        </div>
    </div>

    <div class="form-group">
        <label>Pais</label>
        <input required name="pais" type="text" class="form-control">
    </div>
    <div class="form-group">
        <label>Cantidad albumes</label>
        <input required name="nAlbums" type="number" class="form-control">
    </div>

    <button type="submit" class="btn btn-primary mt-2">Agregar autor</button>
</form>
