<h1>Editar autor</h1>
<form action="<?= BASE_URL ?>update-autor/<?= $autor->ID_Autor ?>" method="POST">
    <!--  Mostrar el formulario con los datos actuales del autor -->
    <label for="name">Nombre:</label>
    <input type="text" name="name" id="name" value="<?= htmlspecialchars($autor->nombre) ?>" required>

    <label for="pais">País:</label>
    <input type="text" name="pais" id="pais" value="<?= htmlspecialchars($autor->pais) ?>" required>

    <label for="nAlbums">Cantidad de Álbumes:</label>
    <input type="number" name="nAlbums" id="nAlbums" value="<?= htmlspecialchars($autor->cantAlbumes) ?>" required>

    <button type="submit">Guardar cambios</button>
</form>