<!DOCTYPE html>
<html lang="en">

<!-- head -->
<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>Titulo</title>
</head>

<body>
    <!-- main header -->
    <header>
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
                <?php if($this->user):?>
                    <ul> 
                        <li class="nav-item">
                                <a class="navbar-brand" href="home-admin">RUIDO DE MAGIA</a>
                        </li>
                        <li>
                            <a  class="nav-link" aria-current="page" href="home-admin">Albumes</a>
                        </li> 
                        <li class="nav-item">
                            <a  class="nav-link" aria-current="page" href="showForm-add-album">Añadir album</a>
                        </li>
                        <li class="nav-item"> 
                            <a  class="nav-link" aria-current="page" href="autores-admin">Autores</a>
                        </li>
                        <li class="nav-item">
                            <a  class="nav-link" aria-current="page" href="showForm-add-autor">Añadir autor</a>
                        </li>
                            <span class ="navbar-text"> Hola, bienvenido: <?= $this->user->username?></span>  
                        <li class="nav-item">
                            <a  class="nav-link" aria-current="page" href="logout">Salir</a>
                        </li>
                        <?php else: ?>
                            <li class="nav-item">
                                <a class="navbar-brand" href="">RUIDO DE MAGIA</a>
                            </li>
                            <li class="nav-item"> 
                            <a  class="nav-link" aria-current="page" href="">Albumes</a>
                            </li>
                            <li class="nav-item"> 
                                <a  class="nav-link" aria-current="page" href="autores">Autores</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="showLogin">Log In</a>
                            </li>
                        <?php endif; ?> 
                    </ul>
                </div>
            </div>
            </nav>
    </header>

    <main class="container mt-3">